import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Geist_Mono, Noto_Sans_Thai, Sarabun } from "next/font/google";
import "./globals.css";
import { AppNavbar } from "@/components/AppNavbar";
import { SWRProvider } from "@/app/provider/SWRProvider";

const notoSansThai = Noto_Sans_Thai({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin", "latin-ext", "thai"],
  variable: "--font-noto-sans-thai",
});
const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  display: "swap",
});

const sarabun = Sarabun({
  variable: "--font-sarabun-family",
  subsets: ["thai", "latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="th"
      className={`${geist.variable} ${geistMono.variable} ${notoSansThai.variable} ${sarabun.variable} h-full antialiased`}
    >
      <body className="min-h-screen bg-background text-foreground">
        <SWRProvider>
        <div className="mx-auto flex min-h-screen w-full flex-col px-4 py-1.5 sm:px-6 lg:px-7">
          
          <Suspense fallback={null}>
            <AppNavbar />
          </Suspense>
          <main className="flex flex-1 flex-col py-8">{children}</main>
        </div>
        </SWRProvider>
      </body>
    </html>
  );
}
